version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and start container
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

      - run:
          name: Install test environment
          command: |
            docker exec -it example_repo bash -c "pip install -r test-requirements.txt"
            docker exec -it example_repo bash -c "pip install coverage coverage-badge"
      
      - run:
          name: Run tests
          command: |
            docker exec -it example_repo bash -c "python setup.py test"
            docker cp example_repo:/example-repo/htmlcov /tmp/artifacts

           
      - run:
          name: Generate coverage badge
          command: |
            docker exec -it example_repo bash -c "coverage-badge -o coverage.svg"
            docker cp example_repo:/example-repo/coverage.svg /tmp/artifacts/
      
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: vanoord
          filters:
            tags:
              only: /.*/